
// ERROR_HANDLING_PREPROCESSING
// 
//   Collection of macros that simplify the use of the error_handling module.
// 
// HISTORY
// 
//   20111109 KP - Initial version
//   20111110 KP - Ported to auto-generated system
//   20120702 (KP) - Re-generated (make autogenerated)
// 
// AUTHOR
// 
//   Koen Poppe, Department of Computer Science,
//   Katholieke Universiteit Leuven, Celestijnenlaan 200A,
//   B-3001 Heverlee, Belgium
//   Email: Koen.Poppe@cs.kuleuven.be
//

// Stringification
#define strstr(x) "x"
#define str(x) strstr(x)

#define CONTINUATION & NEWLINE            


// assert_eq
#define __precondition(a) \
	call assert_eq( a,.true.,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_ifail(a) \
	call assert_eq( a,.true.,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __preconditionc(a,the_comment) \
	call assert_eq( a,.true.,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_ifailc(a,the_comment) \
	call assert_eq( a,.true.,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __precondition_eq(a,b) \
    call precondition_eq( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_eq_ifail(a,b) \
    call precondition_eq( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __precondition_eqc(a,b,the_comment) \
    call precondition_eq( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_eq_ifailc(a,b,the_comment) \
    call precondition_eq( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition(a) \
	call assert_eq( a,.true.,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_ifail(a) \
	call assert_eq( a,.true.,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postconditionc(a,the_comment) \
	call assert_eq( a,.true.,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_ifailc(a,the_comment) \
	call assert_eq( a,.true.,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_eq(a,b) \
    call postcondition_eq( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_eq_ifail(a,b) \
    call postcondition_eq( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_eqc(a,b,the_comment) \
    call postcondition_eq( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_eq_ifailc(a,b,the_comment) \
    call postcondition_eq( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check(a) \
	call assert_eq( a,.true.,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_ifail(a) \
	call assert_eq( a,.true.,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __checkc(a,the_comment) \
	call assert_eq( a,.true.,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_ifailc(a,the_comment) \
	call assert_eq( a,.true.,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_eq(a,b) \
    call check_eq( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_eq_ifail(a,b) \
    call check_eq( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_eqc(a,b,the_comment) \
    call check_eq( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_eq_ifailc(a,b,the_comment) \
    call check_eq( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest(a) \
	call assert_eq( a,.true.,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_ifail(a) \
	call assert_eq( a,.true.,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittestc(a,the_comment) \
	call assert_eq( a,.true.,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_ifailc(a,the_comment) \
	call assert_eq( a,.true.,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_eq(a,b) \
    call unittest_eq( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_eq_ifail(a,b) \
    call unittest_eq( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_eqc(a,b,the_comment) \
    call unittest_eq( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_eq_ifailc(a,b,the_comment) \
    call unittest_eq( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return

// assert_ne
#define __precondition_ne(a,b) \
    call precondition_ne( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_ne_ifail(a,b) \
    call precondition_ne( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __precondition_nec(a,b,the_comment) \
    call precondition_ne( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_ne_ifailc(a,b,the_comment) \
    call precondition_ne( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_ne(a,b) \
    call postcondition_ne( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_ne_ifail(a,b) \
    call postcondition_ne( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_nec(a,b,the_comment) \
    call postcondition_ne( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_ne_ifailc(a,b,the_comment) \
    call postcondition_ne( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_ne(a,b) \
    call check_ne( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_ne_ifail(a,b) \
    call check_ne( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_nec(a,b,the_comment) \
    call check_ne( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_ne_ifailc(a,b,the_comment) \
    call check_ne( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_ne(a,b) \
    call unittest_ne( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_ne_ifail(a,b) \
    call unittest_ne( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_nec(a,b,the_comment) \
    call unittest_ne( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_ne_ifailc(a,b,the_comment) \
    call unittest_ne( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return

// assert_lt
#define __precondition_lt(a,b) \
    call precondition_lt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_lt_ifail(a,b) \
    call precondition_lt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __precondition_ltc(a,b,the_comment) \
    call precondition_lt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_lt_ifailc(a,b,the_comment) \
    call precondition_lt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_lt(a,b) \
    call postcondition_lt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_lt_ifail(a,b) \
    call postcondition_lt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_ltc(a,b,the_comment) \
    call postcondition_lt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_lt_ifailc(a,b,the_comment) \
    call postcondition_lt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_lt(a,b) \
    call check_lt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_lt_ifail(a,b) \
    call check_lt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_ltc(a,b,the_comment) \
    call check_lt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_lt_ifailc(a,b,the_comment) \
    call check_lt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_lt(a,b) \
    call unittest_lt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_lt_ifail(a,b) \
    call unittest_lt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_ltc(a,b,the_comment) \
    call unittest_lt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_lt_ifailc(a,b,the_comment) \
    call unittest_lt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return

// assert_le
#define __precondition_le(a,b) \
    call precondition_le( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_le_ifail(a,b) \
    call precondition_le( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __precondition_lec(a,b,the_comment) \
    call precondition_le( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_le_ifailc(a,b,the_comment) \
    call precondition_le( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_le(a,b) \
    call postcondition_le( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_le_ifail(a,b) \
    call postcondition_le( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_lec(a,b,the_comment) \
    call postcondition_le( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_le_ifailc(a,b,the_comment) \
    call postcondition_le( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_le(a,b) \
    call check_le( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_le_ifail(a,b) \
    call check_le( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_lec(a,b,the_comment) \
    call check_le( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_le_ifailc(a,b,the_comment) \
    call check_le( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_le(a,b) \
    call unittest_le( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_le_ifail(a,b) \
    call unittest_le( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_lec(a,b,the_comment) \
    call unittest_le( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_le_ifailc(a,b,the_comment) \
    call unittest_le( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return

// assert_gt
#define __precondition_gt(a,b) \
    call precondition_gt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_gt_ifail(a,b) \
    call precondition_gt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __precondition_gtc(a,b,the_comment) \
    call precondition_gt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_gt_ifailc(a,b,the_comment) \
    call precondition_gt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_gt(a,b) \
    call postcondition_gt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_gt_ifail(a,b) \
    call postcondition_gt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_gtc(a,b,the_comment) \
    call postcondition_gt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_gt_ifailc(a,b,the_comment) \
    call postcondition_gt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_gt(a,b) \
    call check_gt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_gt_ifail(a,b) \
    call check_gt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_gtc(a,b,the_comment) \
    call check_gt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_gt_ifailc(a,b,the_comment) \
    call check_gt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_gt(a,b) \
    call unittest_gt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_gt_ifail(a,b) \
    call unittest_gt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_gtc(a,b,the_comment) \
    call unittest_gt( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_gt_ifailc(a,b,the_comment) \
    call unittest_gt( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return

// assert_ge
#define __precondition_ge(a,b) \
    call precondition_ge( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_ge_ifail(a,b) \
    call precondition_ge( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __precondition_gec(a,b,the_comment) \
    call precondition_ge( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_ge_ifailc(a,b,the_comment) \
    call precondition_ge( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_ge(a,b) \
    call postcondition_ge( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_ge_ifail(a,b) \
    call postcondition_ge( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_gec(a,b,the_comment) \
    call postcondition_ge( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_ge_ifailc(a,b,the_comment) \
    call postcondition_ge( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_ge(a,b) \
    call check_ge( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_ge_ifail(a,b) \
    call check_ge( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_gec(a,b,the_comment) \
    call check_ge( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_ge_ifailc(a,b,the_comment) \
    call check_ge( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_ge(a,b) \
    call unittest_ge( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_ge_ifail(a,b) \
    call unittest_ge( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_gec(a,b,the_comment) \
    call unittest_ge( a,b,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_ge_ifailc(a,b,the_comment) \
    call unittest_ge( a,b,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return

// assert_abserr
#define __precondition_abserr(a,b,epsabs) \
    call precondition_abserr( a,b,epsabs,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_abserr_ifail(a,b,epsabs) \
    call precondition_abserr( a,b,epsabs,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __precondition_abserrc(a,b,epsabs,the_comment) \
    call precondition_abserr( a,b,epsabs,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_abserr_ifailc(a,b,epsabs,the_comment) \
    call precondition_abserr( a,b,epsabs,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_abserr(a,b,epsabs) \
    call postcondition_abserr( a,b,epsabs,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_abserr_ifail(a,b,epsabs) \
    call postcondition_abserr( a,b,epsabs,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_abserrc(a,b,epsabs,the_comment) \
    call postcondition_abserr( a,b,epsabs,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_abserr_ifailc(a,b,epsabs,the_comment) \
    call postcondition_abserr( a,b,epsabs,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_abserr(a,b,epsabs) \
    call check_abserr( a,b,epsabs,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_abserr_ifail(a,b,epsabs) \
    call check_abserr( a,b,epsabs,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_abserrc(a,b,epsabs,the_comment) \
    call check_abserr( a,b,epsabs,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_abserr_ifailc(a,b,epsabs,the_comment) \
    call check_abserr( a,b,epsabs,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_abserr(a,b,epsabs) \
    call unittest_abserr( a,b,epsabs,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_abserr_ifail(a,b,epsabs) \
    call unittest_abserr( a,b,epsabs,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_abserrc(a,b,epsabs,the_comment) \
    call unittest_abserr( a,b,epsabs,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_abserr_ifailc(a,b,epsabs,the_comment) \
    call unittest_abserr( a,b,epsabs,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return

// assert_relerr
#define __precondition_relerr(a,b,epsrel) \
    call precondition_relerr( a,b,epsrel,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_relerr_ifail(a,b,epsrel) \
    call precondition_relerr( a,b,epsrel,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __precondition_relerrc(a,b,epsrel,the_comment) \
    call precondition_relerr( a,b,epsrel,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __precondition_relerr_ifailc(a,b,epsrel,the_comment) \
    call precondition_relerr( a,b,epsrel,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_relerr(a,b,epsrel) \
    call postcondition_relerr( a,b,epsrel,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_relerr_ifail(a,b,epsrel) \
    call postcondition_relerr( a,b,epsrel,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __postcondition_relerrc(a,b,epsrel,the_comment) \
    call postcondition_relerr( a,b,epsrel,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __postcondition_relerr_ifailc(a,b,epsrel,the_comment) \
    call postcondition_relerr( a,b,epsrel,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_relerr(a,b,epsrel) \
    call check_relerr( a,b,epsrel,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_relerr_ifail(a,b,epsrel) \
    call check_relerr( a,b,epsrel,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __check_relerrc(a,b,epsrel,the_comment) \
    call check_relerr( a,b,epsrel,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __check_relerr_ifailc(a,b,epsrel,the_comment) \
    call check_relerr( a,b,epsrel,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_relerr(a,b,epsrel) \
    call unittest_relerr( a,b,epsrel,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_relerr_ifail(a,b,epsrel) \
    call unittest_relerr( a,b,epsrel,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return
#define __unittest_relerrc(a,b,epsrel,the_comment) \
    call unittest_relerr( a,b,epsrel,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ )
#define __unittest_relerr_ifailc(a,b,epsrel,the_comment) \
    call unittest_relerr( a,b,epsrel,ifail=ifail,CONTINUATION a_name=str(a),b_name=str(b),CONTINUATION comment=the_comment,CONTINUATION filename=__FILE__,line=__LINE__ ); NEWLINE\
        if( is_error(ifail) ) return


// Error class
        
#define __precondition_errorclass(ifail,error_info_type) \
    __precondition( is_error(ifail) ) NEWLINE \
        if( is_error(ifail) ) then NEWLINE \
            select type( info=>ifail%info ) NEWLINE \
                class is( error_info_type ) NEWLINE \
                    call precondition( .true., comment="The expected error_info_type" ) NEWLINE \
                class default NEWLINE \
                    call precondition( .false., comment="Expect error_info_type, but got something else", reason=ifail )NEWLINE \
            end selectNEWLINE \
        end if
        
#define __postcondition_errorclass(ifail,error_info_type) \
    __postcondition( is_error(ifail) ) NEWLINE \
        if( is_error(ifail) ) then NEWLINE \
            select type( info=>ifail%info ) NEWLINE \
                class is( error_info_type ) NEWLINE \
                    call postcondition( .true., comment="The expected error_info_type" ) NEWLINE \
                class default NEWLINE \
                    call postcondition( .false., comment="Expect error_info_type, but got something else", reason=ifail )NEWLINE \
            end selectNEWLINE \
        end if
        
#define __check_errorclass(ifail,error_info_type) \
    __check( is_error(ifail) ) NEWLINE \
        if( is_error(ifail) ) then NEWLINE \
            select type( info=>ifail%info ) NEWLINE \
                class is( error_info_type ) NEWLINE \
                    call check( .true., comment="The expected error_info_type" ) NEWLINE \
                class default NEWLINE \
                    call check( .false., comment="Expect error_info_type, but got something else", reason=ifail )NEWLINE \
            end selectNEWLINE \
        end if
        
#define __unittest_errorclass(ifail,error_info_type) \
    __unittest( is_error(ifail) ) NEWLINE \
        if( is_error(ifail) ) then NEWLINE \
            select type( info=>ifail%info ) NEWLINE \
                class is( error_info_type ) NEWLINE \
                    call unittest( .true., comment="The expected error_info_type" ) NEWLINE \
                class default NEWLINE \
                    call unittest( .false., comment="Expect error_info_type, but got something else", reason=ifail )NEWLINE \
            end selectNEWLINE \
        end if
        